CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100),
    uid VARCHAR(100) UNIQUE
);

CREATE TABLE absensi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100),
    uid VARCHAR(100),
    waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);